### ISSUE TITLE
serviceAdded() Callback for Powered Off Device?

### ISSUE THREAD

**Issue by wumpus7** [jbagg/QtZeroConf#12]
Howdy,

I'm seeing behavior from the browser that I can't account for, so I wonder if I'm misunderstanding how things are supposed to work, or if there's a bug.

Repro:

1) Power up a device that publishes it service name via Bonjour - in my case, a speaker.
2) Create a QZeroConf browser, connect up serviceAdded(), etc., and call startBrowser().
3) See that the device is added by the browser (callback via serviceAdded()).
4) Power down the device.  (Note that the device doesn't send a 'lost' or 'removed' or whatever message on power down - it doesn't have the ability to send a last message during power off.)
5) Call stopBrowser() followed by startBrowser().
6) See that the device is added by the browser!

The weirdness is not that the device is rediscovered - I'm sure it's persisting in various Bonjour caches on the network.  The weirdness is that I thought that QtZeroConf had a resolution step before it added a device, and I don't think it's possible to resolve a device that isn't physically present on the network?  Or is that also handled indirectly via cached records?

Does QtZeroConf 'remember' that it resolved the device previously and just use the old information (since it hasn't gotten any Bonjour notification about the device going away)?  This assumes that a 'real' resolution pass happened initially.

Also, what is the resolution timeout?

Thoughts?

Thanks,
Alex

**Comment by jbagg** [comment]
What OS do you see this happening on (iOS)?  On Ubuntu, the OS caches the resolve for just over a min.  When I follow your procedure, I also see serviceAdded() firing for the device that doesn't exist.  If you wait 1.5 min (on Ubuntu 16.04) before starting the browser then serviceAdded() will not fire as the resolve will fail.

I did find a bug........If you don't stop the browser, you are supposed to see the service disappear after about a min (on Ubuntu 16.04) when the resolve cache is updated.  This bug is only confirmed for QtZeroConf backends that use Avahi.  I'm not sure yet what the dnssd backend is doing in this situation....will check on the weekend. I need to keep the AvahiServiceResolvers around to get updates.

> The weirdness is that I thought that QtZeroConf had a resolution step before it added a device

Correct, QtZeroConf will not emit serviceAdded() unless it can successfully resolve the service.  (problem is OS cache described above)

**Comment by wumpus7** [comment]
I'm using macOS currently.  I don't think this caching behavior depends on OS, though - it's probably generic to Bonjour.

I do occasionally see service removed notifications - presumably when I manage to wait long enough for it to expire from the cache.  If I recall correctly, much of Bonjour operates on exponential backoffs to reduce traffic; I wouldn't be surprised if the time for the cache to purge a powered off device was variable, and possibly dependent on the time it had been on.

I've also seen what looked like spurious removals - speakers that are currently powered up suddenly reported as lost, despite the fact that I'm currently connected to them.  Any idea why that might happen?

Thanks,
Alex

**Comment by jbagg** [comment]
I tested the dnssd backend (same used on Mac) on Windows and it is working which is consistent with your findings on Mac, so I think it is just the Avahi code.

> I've also seen what looked like spurious removals - speakers that are currently powered up suddenly reported as lost, despite the fact that I'm currently connected to them. 

Are these speakers / devices on wifi?  Have you connected to error(QZeroConf::error_t) and do you see any errors?  I've got a Mac and 2 linux PCs I'm going to run overnight.

**Comment by wumpus7** [comment]
Yes, they are connected via a wifi router, and yes I'm monitoring all error signals and have seen no errors.

**Comment by jbagg** [comment]
I suspect it is the wifi.  multicast on wifi has been a disaster.  I've just run the example on 2 linux PCs +  Mac book for 36 hours (all wired).  There was no extra removes / adds... only the original service discoveries, one for each.
